title: "MMS Strategy Documentation"
description: "Micro Meme Strategy - Professional treasury management through active meme coin rotation"
baseurl: ""
url: ""

# Use GitHub Pages compatible theme
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM

# Site settings
author: "MMS Strategy Team"
